// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RpcRequest.proto

package com.bobby.rpc.core.common.protobuf;

public final class RpcRequestProto {
  private RpcRequestProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface RpcRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:RpcRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string interface_name = 1;</code>
     * @return The interfaceName.
     */
    String getInterfaceName();
    /**
     * <code>string interface_name = 1;</code>
     * @return The bytes for interfaceName.
     */
    com.google.protobuf.ByteString
        getInterfaceNameBytes();

    /**
     * <code>string method_name = 2;</code>
     * @return The methodName.
     */
    String getMethodName();
    /**
     * <code>string method_name = 2;</code>
     * @return The bytes for methodName.
     */
    com.google.protobuf.ByteString
        getMethodNameBytes();

    /**
     * <pre>
     * 参数值序列化后的字节数组
     * </pre>
     *
     * <code>repeated bytes params = 3;</code>
     * @return A list containing the params.
     */
    java.util.List<com.google.protobuf.ByteString> getParamsList();
    /**
     * <pre>
     * 参数值序列化后的字节数组
     * </pre>
     *
     * <code>repeated bytes params = 3;</code>
     * @return The count of params.
     */
    int getParamsCount();
    /**
     * <pre>
     * 参数值序列化后的字节数组
     * </pre>
     *
     * <code>repeated bytes params = 3;</code>
     * @param index The index of the element to return.
     * @return The params at the given index.
     */
    com.google.protobuf.ByteString getParams(int index);

    /**
     * <pre>
     * 参数类型的全限定类名
     * </pre>
     *
     * <code>repeated string params_types = 4;</code>
     * @return A list containing the paramsTypes.
     */
    java.util.List<String>
        getParamsTypesList();
    /**
     * <pre>
     * 参数类型的全限定类名
     * </pre>
     *
     * <code>repeated string params_types = 4;</code>
     * @return The count of paramsTypes.
     */
    int getParamsTypesCount();
    /**
     * <pre>
     * 参数类型的全限定类名
     * </pre>
     *
     * <code>repeated string params_types = 4;</code>
     * @param index The index of the element to return.
     * @return The paramsTypes at the given index.
     */
    String getParamsTypes(int index);
    /**
     * <pre>
     * 参数类型的全限定类名
     * </pre>
     *
     * <code>repeated string params_types = 4;</code>
     * @param index The index of the value to return.
     * @return The bytes of the paramsTypes at the given index.
     */
    com.google.protobuf.ByteString
        getParamsTypesBytes(int index);

    /**
     * <code>.RpcRequest.RequestType type = 5;</code>
     * @return The enum numeric value on the wire for type.
     */
    int getTypeValue();
    /**
     * <code>.RpcRequest.RequestType type = 5;</code>
     * @return The type.
     */
    RpcRequest.RequestType getType();
  }
  /**
   * Protobuf type {@code RpcRequest}
   */
  public static final class RpcRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:RpcRequest)
      RpcRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use RpcRequest.newBuilder() to construct.
    private RpcRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RpcRequest() {
      interfaceName_ = "";
      methodName_ = "";
      params_ = java.util.Collections.emptyList();
      paramsTypes_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      type_ = 0;
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new RpcRequest();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return internal_static_RpcRequest_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return internal_static_RpcRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              RpcRequest.class, Builder.class);
    }

    /**
     * Protobuf enum {@code RpcRequest.RequestType}
     */
    public enum RequestType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>NORMAL = 0;</code>
       */
      NORMAL(0),
      /**
       * <code>HEARTBEAT = 1;</code>
       */
      HEARTBEAT(1),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>NORMAL = 0;</code>
       */
      public static final int NORMAL_VALUE = 0;
      /**
       * <code>HEARTBEAT = 1;</code>
       */
      public static final int HEARTBEAT_VALUE = 1;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @Deprecated
      public static RequestType valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static RequestType forNumber(int value) {
        switch (value) {
          case 0: return NORMAL;
          case 1: return HEARTBEAT;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<RequestType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          RequestType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<RequestType>() {
              public RequestType findValueByNumber(int number) {
                return RequestType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        if (this == UNRECOGNIZED) {
          throw new IllegalStateException(
              "Can't get the descriptor of an unrecognized enum value.");
        }
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return RpcRequest.getDescriptor().getEnumTypes().get(0);
      }

      private static final RequestType[] VALUES = values();

      public static RequestType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private RequestType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:RpcRequest.RequestType)
    }

    public static final int INTERFACE_NAME_FIELD_NUMBER = 1;
    private volatile Object interfaceName_;
    /**
     * <code>string interface_name = 1;</code>
     * @return The interfaceName.
     */
    @Override
    public String getInterfaceName() {
      Object ref = interfaceName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        interfaceName_ = s;
        return s;
      }
    }
    /**
     * <code>string interface_name = 1;</code>
     * @return The bytes for interfaceName.
     */
    @Override
    public com.google.protobuf.ByteString
        getInterfaceNameBytes() {
      Object ref = interfaceName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        interfaceName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int METHOD_NAME_FIELD_NUMBER = 2;
    private volatile Object methodName_;
    /**
     * <code>string method_name = 2;</code>
     * @return The methodName.
     */
    @Override
    public String getMethodName() {
      Object ref = methodName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        methodName_ = s;
        return s;
      }
    }
    /**
     * <code>string method_name = 2;</code>
     * @return The bytes for methodName.
     */
    @Override
    public com.google.protobuf.ByteString
        getMethodNameBytes() {
      Object ref = methodName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        methodName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PARAMS_FIELD_NUMBER = 3;
    private java.util.List<com.google.protobuf.ByteString> params_;
    /**
     * <pre>
     * 参数值序列化后的字节数组
     * </pre>
     *
     * <code>repeated bytes params = 3;</code>
     * @return A list containing the params.
     */
    @Override
    public java.util.List<com.google.protobuf.ByteString>
        getParamsList() {
      return params_;
    }
    /**
     * <pre>
     * 参数值序列化后的字节数组
     * </pre>
     *
     * <code>repeated bytes params = 3;</code>
     * @return The count of params.
     */
    public int getParamsCount() {
      return params_.size();
    }
    /**
     * <pre>
     * 参数值序列化后的字节数组
     * </pre>
     *
     * <code>repeated bytes params = 3;</code>
     * @param index The index of the element to return.
     * @return The params at the given index.
     */
    public com.google.protobuf.ByteString getParams(int index) {
      return params_.get(index);
    }

    public static final int PARAMS_TYPES_FIELD_NUMBER = 4;
    private com.google.protobuf.LazyStringList paramsTypes_;
    /**
     * <pre>
     * 参数类型的全限定类名
     * </pre>
     *
     * <code>repeated string params_types = 4;</code>
     * @return A list containing the paramsTypes.
     */
    public com.google.protobuf.ProtocolStringList
        getParamsTypesList() {
      return paramsTypes_;
    }
    /**
     * <pre>
     * 参数类型的全限定类名
     * </pre>
     *
     * <code>repeated string params_types = 4;</code>
     * @return The count of paramsTypes.
     */
    public int getParamsTypesCount() {
      return paramsTypes_.size();
    }
    /**
     * <pre>
     * 参数类型的全限定类名
     * </pre>
     *
     * <code>repeated string params_types = 4;</code>
     * @param index The index of the element to return.
     * @return The paramsTypes at the given index.
     */
    public String getParamsTypes(int index) {
      return paramsTypes_.get(index);
    }
    /**
     * <pre>
     * 参数类型的全限定类名
     * </pre>
     *
     * <code>repeated string params_types = 4;</code>
     * @param index The index of the value to return.
     * @return The bytes of the paramsTypes at the given index.
     */
    public com.google.protobuf.ByteString
        getParamsTypesBytes(int index) {
      return paramsTypes_.getByteString(index);
    }

    public static final int TYPE_FIELD_NUMBER = 5;
    private int type_;
    /**
     * <code>.RpcRequest.RequestType type = 5;</code>
     * @return The enum numeric value on the wire for type.
     */
    @Override public int getTypeValue() {
      return type_;
    }
    /**
     * <code>.RpcRequest.RequestType type = 5;</code>
     * @return The type.
     */
    @Override public RequestType getType() {
      @SuppressWarnings("deprecation")
      RequestType result = RequestType.valueOf(type_);
      return result == null ? RequestType.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(interfaceName_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, interfaceName_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(methodName_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, methodName_);
      }
      for (int i = 0; i < params_.size(); i++) {
        output.writeBytes(3, params_.get(i));
      }
      for (int i = 0; i < paramsTypes_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, paramsTypes_.getRaw(i));
      }
      if (type_ != RequestType.NORMAL.getNumber()) {
        output.writeEnum(5, type_);
      }
      getUnknownFields().writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(interfaceName_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, interfaceName_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(methodName_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, methodName_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < params_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(params_.get(i));
        }
        size += dataSize;
        size += 1 * getParamsList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < paramsTypes_.size(); i++) {
          dataSize += computeStringSizeNoTag(paramsTypes_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getParamsTypesList().size();
      }
      if (type_ != RequestType.NORMAL.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(5, type_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof RpcRequest)) {
        return super.equals(obj);
      }
      RpcRequest other = (RpcRequest) obj;

      if (!getInterfaceName()
          .equals(other.getInterfaceName())) return false;
      if (!getMethodName()
          .equals(other.getMethodName())) return false;
      if (!getParamsList()
          .equals(other.getParamsList())) return false;
      if (!getParamsTypesList()
          .equals(other.getParamsTypesList())) return false;
      if (type_ != other.type_) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + INTERFACE_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getInterfaceName().hashCode();
      hash = (37 * hash) + METHOD_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getMethodName().hashCode();
      if (getParamsCount() > 0) {
        hash = (37 * hash) + PARAMS_FIELD_NUMBER;
        hash = (53 * hash) + getParamsList().hashCode();
      }
      if (getParamsTypesCount() > 0) {
        hash = (37 * hash) + PARAMS_TYPES_FIELD_NUMBER;
        hash = (53 * hash) + getParamsTypesList().hashCode();
      }
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + type_;
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static RpcRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static RpcRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static RpcRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static RpcRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static RpcRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static RpcRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static RpcRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static RpcRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static RpcRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static RpcRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static RpcRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static RpcRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(RpcRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code RpcRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:RpcRequest)
        RpcRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return internal_static_RpcRequest_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return internal_static_RpcRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                RpcRequest.class, Builder.class);
      }

      // Construct using com.bobby.rpc.core.common.protobuf.RpcRequestProto.RpcRequest.newBuilder()
      private Builder() {

      }

      private Builder(
          BuilderParent parent) {
        super(parent);

      }
      @Override
      public Builder clear() {
        super.clear();
        interfaceName_ = "";

        methodName_ = "";

        params_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        paramsTypes_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        type_ = 0;

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return internal_static_RpcRequest_descriptor;
      }

      @Override
      public RpcRequest getDefaultInstanceForType() {
        return getDefaultInstance();
      }

      @Override
      public RpcRequest build() {
        RpcRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public RpcRequest buildPartial() {
        RpcRequest result = new RpcRequest(this);
        int from_bitField0_ = bitField0_;
        result.interfaceName_ = interfaceName_;
        result.methodName_ = methodName_;
        if (((bitField0_ & 0x00000001) != 0)) {
          params_ = java.util.Collections.unmodifiableList(params_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.params_ = params_;
        if (((bitField0_ & 0x00000002) != 0)) {
          paramsTypes_ = paramsTypes_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.paramsTypes_ = paramsTypes_;
        result.type_ = type_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof RpcRequest) {
          return mergeFrom((RpcRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(RpcRequest other) {
        if (other == getDefaultInstance()) return this;
        if (!other.getInterfaceName().isEmpty()) {
          interfaceName_ = other.interfaceName_;
          onChanged();
        }
        if (!other.getMethodName().isEmpty()) {
          methodName_ = other.methodName_;
          onChanged();
        }
        if (!other.params_.isEmpty()) {
          if (params_.isEmpty()) {
            params_ = other.params_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureParamsIsMutable();
            params_.addAll(other.params_);
          }
          onChanged();
        }
        if (!other.paramsTypes_.isEmpty()) {
          if (paramsTypes_.isEmpty()) {
            paramsTypes_ = other.paramsTypes_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureParamsTypesIsMutable();
            paramsTypes_.addAll(other.paramsTypes_);
          }
          onChanged();
        }
        if (other.type_ != 0) {
          setTypeValue(other.getTypeValue());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                interfaceName_ = input.readStringRequireUtf8();

                break;
              } // case 10
              case 18: {
                methodName_ = input.readStringRequireUtf8();

                break;
              } // case 18
              case 26: {
                com.google.protobuf.ByteString v = input.readBytes();
                ensureParamsIsMutable();
                params_.add(v);
                break;
              } // case 26
              case 34: {
                String s = input.readStringRequireUtf8();
                ensureParamsTypesIsMutable();
                paramsTypes_.add(s);
                break;
              } // case 34
              case 40: {
                type_ = input.readEnum();

                break;
              } // case 40
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private Object interfaceName_ = "";
      /**
       * <code>string interface_name = 1;</code>
       * @return The interfaceName.
       */
      public String getInterfaceName() {
        Object ref = interfaceName_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          interfaceName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string interface_name = 1;</code>
       * @return The bytes for interfaceName.
       */
      public com.google.protobuf.ByteString
          getInterfaceNameBytes() {
        Object ref = interfaceName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          interfaceName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string interface_name = 1;</code>
       * @param value The interfaceName to set.
       * @return This builder for chaining.
       */
      public Builder setInterfaceName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        interfaceName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string interface_name = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearInterfaceName() {
        
        interfaceName_ = getDefaultInstance().getInterfaceName();
        onChanged();
        return this;
      }
      /**
       * <code>string interface_name = 1;</code>
       * @param value The bytes for interfaceName to set.
       * @return This builder for chaining.
       */
      public Builder setInterfaceNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        interfaceName_ = value;
        onChanged();
        return this;
      }

      private Object methodName_ = "";
      /**
       * <code>string method_name = 2;</code>
       * @return The methodName.
       */
      public String getMethodName() {
        Object ref = methodName_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          methodName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string method_name = 2;</code>
       * @return The bytes for methodName.
       */
      public com.google.protobuf.ByteString
          getMethodNameBytes() {
        Object ref = methodName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          methodName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string method_name = 2;</code>
       * @param value The methodName to set.
       * @return This builder for chaining.
       */
      public Builder setMethodName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        methodName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string method_name = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearMethodName() {
        
        methodName_ = getDefaultInstance().getMethodName();
        onChanged();
        return this;
      }
      /**
       * <code>string method_name = 2;</code>
       * @param value The bytes for methodName to set.
       * @return This builder for chaining.
       */
      public Builder setMethodNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        methodName_ = value;
        onChanged();
        return this;
      }

      private java.util.List<com.google.protobuf.ByteString> params_ = java.util.Collections.emptyList();
      private void ensureParamsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          params_ = new java.util.ArrayList<com.google.protobuf.ByteString>(params_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <pre>
       * 参数值序列化后的字节数组
       * </pre>
       *
       * <code>repeated bytes params = 3;</code>
       * @return A list containing the params.
       */
      public java.util.List<com.google.protobuf.ByteString>
          getParamsList() {
        return ((bitField0_ & 0x00000001) != 0) ?
                 java.util.Collections.unmodifiableList(params_) : params_;
      }
      /**
       * <pre>
       * 参数值序列化后的字节数组
       * </pre>
       *
       * <code>repeated bytes params = 3;</code>
       * @return The count of params.
       */
      public int getParamsCount() {
        return params_.size();
      }
      /**
       * <pre>
       * 参数值序列化后的字节数组
       * </pre>
       *
       * <code>repeated bytes params = 3;</code>
       * @param index The index of the element to return.
       * @return The params at the given index.
       */
      public com.google.protobuf.ByteString getParams(int index) {
        return params_.get(index);
      }
      /**
       * <pre>
       * 参数值序列化后的字节数组
       * </pre>
       *
       * <code>repeated bytes params = 3;</code>
       * @param index The index to set the value at.
       * @param value The params to set.
       * @return This builder for chaining.
       */
      public Builder setParams(
          int index, com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureParamsIsMutable();
        params_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 参数值序列化后的字节数组
       * </pre>
       *
       * <code>repeated bytes params = 3;</code>
       * @param value The params to add.
       * @return This builder for chaining.
       */
      public Builder addParams(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureParamsIsMutable();
        params_.add(value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 参数值序列化后的字节数组
       * </pre>
       *
       * <code>repeated bytes params = 3;</code>
       * @param values The params to add.
       * @return This builder for chaining.
       */
      public Builder addAllParams(
          Iterable<? extends com.google.protobuf.ByteString> values) {
        ensureParamsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, params_);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 参数值序列化后的字节数组
       * </pre>
       *
       * <code>repeated bytes params = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearParams() {
        params_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList paramsTypes_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureParamsTypesIsMutable() {
        if (!((bitField0_ & 0x00000002) != 0)) {
          paramsTypes_ = new com.google.protobuf.LazyStringArrayList(paramsTypes_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <pre>
       * 参数类型的全限定类名
       * </pre>
       *
       * <code>repeated string params_types = 4;</code>
       * @return A list containing the paramsTypes.
       */
      public com.google.protobuf.ProtocolStringList
          getParamsTypesList() {
        return paramsTypes_.getUnmodifiableView();
      }
      /**
       * <pre>
       * 参数类型的全限定类名
       * </pre>
       *
       * <code>repeated string params_types = 4;</code>
       * @return The count of paramsTypes.
       */
      public int getParamsTypesCount() {
        return paramsTypes_.size();
      }
      /**
       * <pre>
       * 参数类型的全限定类名
       * </pre>
       *
       * <code>repeated string params_types = 4;</code>
       * @param index The index of the element to return.
       * @return The paramsTypes at the given index.
       */
      public String getParamsTypes(int index) {
        return paramsTypes_.get(index);
      }
      /**
       * <pre>
       * 参数类型的全限定类名
       * </pre>
       *
       * <code>repeated string params_types = 4;</code>
       * @param index The index of the value to return.
       * @return The bytes of the paramsTypes at the given index.
       */
      public com.google.protobuf.ByteString
          getParamsTypesBytes(int index) {
        return paramsTypes_.getByteString(index);
      }
      /**
       * <pre>
       * 参数类型的全限定类名
       * </pre>
       *
       * <code>repeated string params_types = 4;</code>
       * @param index The index to set the value at.
       * @param value The paramsTypes to set.
       * @return This builder for chaining.
       */
      public Builder setParamsTypes(
          int index, String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureParamsTypesIsMutable();
        paramsTypes_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 参数类型的全限定类名
       * </pre>
       *
       * <code>repeated string params_types = 4;</code>
       * @param value The paramsTypes to add.
       * @return This builder for chaining.
       */
      public Builder addParamsTypes(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureParamsTypesIsMutable();
        paramsTypes_.add(value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 参数类型的全限定类名
       * </pre>
       *
       * <code>repeated string params_types = 4;</code>
       * @param values The paramsTypes to add.
       * @return This builder for chaining.
       */
      public Builder addAllParamsTypes(
          Iterable<String> values) {
        ensureParamsTypesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, paramsTypes_);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 参数类型的全限定类名
       * </pre>
       *
       * <code>repeated string params_types = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearParamsTypes() {
        paramsTypes_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 参数类型的全限定类名
       * </pre>
       *
       * <code>repeated string params_types = 4;</code>
       * @param value The bytes of the paramsTypes to add.
       * @return This builder for chaining.
       */
      public Builder addParamsTypesBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureParamsTypesIsMutable();
        paramsTypes_.add(value);
        onChanged();
        return this;
      }

      private int type_ = 0;
      /**
       * <code>.RpcRequest.RequestType type = 5;</code>
       * @return The enum numeric value on the wire for type.
       */
      @Override public int getTypeValue() {
        return type_;
      }
      /**
       * <code>.RpcRequest.RequestType type = 5;</code>
       * @param value The enum numeric value on the wire for type to set.
       * @return This builder for chaining.
       */
      public Builder setTypeValue(int value) {
        
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.RpcRequest.RequestType type = 5;</code>
       * @return The type.
       */
      @Override
      public RequestType getType() {
        @SuppressWarnings("deprecation")
        RequestType result = RequestType.valueOf(type_);
        return result == null ? RequestType.UNRECOGNIZED : result;
      }
      /**
       * <code>.RpcRequest.RequestType type = 5;</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(RequestType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.RpcRequest.RequestType type = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:RpcRequest)
    }

    // @@protoc_insertion_point(class_scope:RpcRequest)
    private static final RpcRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new RpcRequest();
    }

    public static RpcRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RpcRequest>
        PARSER = new com.google.protobuf.AbstractParser<RpcRequest>() {
      @Override
      public RpcRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<RpcRequest> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<RpcRequest> getParserForType() {
      return PARSER;
    }

    @Override
    public RpcRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RpcRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RpcRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\020RpcRequest.proto\"\260\001\n\nRpcRequest\022\026\n\016int" +
      "erface_name\030\001 \001(\t\022\023\n\013method_name\030\002 \001(\t\022\016" +
      "\n\006params\030\003 \003(\014\022\024\n\014params_types\030\004 \003(\t\022%\n\004" +
      "type\030\005 \001(\0162\027.RpcRequest.RequestType\"(\n\013R" +
      "equestType\022\n\n\006NORMAL\020\000\022\r\n\tHEARTBEAT\020\001B7\n" +
      "\"com.bobby.rpc.core.common.protobufB\017Rpc" +
      "RequestProtoP\000b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_RpcRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_RpcRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RpcRequest_descriptor,
        new String[] { "InterfaceName", "MethodName", "Params", "ParamsTypes", "Type", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
